//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SS.Core.Entities
{
    public partial class AfectacionIncidente
    {
        public int Id { get; set; }
        public int IncidenteId { get; set; }
        public int TipoAfectacionId { get; set; }
    
        public virtual TipoAfectacion TipoAfectacion { get; set; }
        public virtual Incidente Incidente { get; set; }
    }
    
}
