//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SS.Core.Entities
{
    public partial class AlertaIncidente
    {
        public int EmpresaId { get; set; }
        public int TipoIncidenteId { get; set; }
        public string Emails { get; set; }
        public bool RecibirOtrasEmpresas { get; set; }
        public bool RecibirMiEmpresa { get; set; }
    
        public virtual TipoIncidente TipoIncidente { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
    
}
