//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SS.Core.Entities
{
    public partial class Empresa
    {
        public Empresa()
        {
            this.Instalaciones = new HashSet<Instalacion>();
            this.Incidentes = new HashSet<Incidente>();
            this.AlertaIncidentes = new HashSet<AlertaIncidente>();
            this.ParametrosSistemaEmpresas = new HashSet<ParametroSistemaEmpresa>();
            this.UsuarioEmpresa = new HashSet<UsuarioEmpresa>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public bool TipoEmpresa { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> GrupoId { get; set; }
    
        public virtual ICollection<Instalacion> Instalaciones { get; set; }
        public virtual ICollection<Incidente> Incidentes { get; set; }
        public virtual ICollection<AlertaIncidente> AlertaIncidentes { get; set; }
        public virtual ICollection<ParametroSistemaEmpresa> ParametrosSistemaEmpresas { get; set; }
        public virtual ICollection<UsuarioEmpresa> UsuarioEmpresa { get; set; }
    }
    
}
