//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SS.Core.Entities
{
    public partial class Estado
    {
        public Estado()
        {
            this.Ciudades = new HashSet<Ciudad>();
            this.Zonas = new HashSet<Zona>();
            this.Incidentes = new HashSet<Incidente>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> PoligonoId { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
    
        public virtual ICollection<Ciudad> Ciudades { get; set; }
        public virtual ICollection<Zona> Zonas { get; set; }
        public virtual ICollection<Incidente> Incidentes { get; set; }
        public virtual Poligono Poligonos { get; set; }
    }
    
}
