//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SS.Core.Entities
{
    public partial class Incidente
    {
        public Incidente()
        {
            this.MontoAfectacion = 0m;
            this.Detenidos = false;
            this.AfectacionIncidentes = new HashSet<AfectacionIncidente>();
        }
    
        public int Id { get; set; }
        public System.DateTime FechaIncidente { get; set; }
        public int EmpresaId { get; set; }
        public int TipoIncidenteId { get; set; }
        public Nullable<int> LesionadosId { get; set; }
        public Nullable<int> TipoInstalacionId { get; set; }
        public Nullable<int> InstalacionId { get; set; }
        public Nullable<decimal> MontoAfectacion { get; set; }
        public string Comentarios { get; set; }
        public double Latitud { get; set; }
        public double Longitud { get; set; }
        public int EstadoId { get; set; }
        public int CiudadId { get; set; }
        public Nullable<int> ZonaId { get; set; }
        public Nullable<int> TipoArmaId { get; set; }
        public Nullable<bool> Detenidos { get; set; }
        public Nullable<int> CantidadDelincuentesId { get; set; }
        public Nullable<int> TipoVehiculoId { get; set; }
        public Nullable<int> TipoExtorsionId { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioCancelacion { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public Nullable<int> UsuarioUltimaModificacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaMoldificacion { get; set; }
        public Nullable<int> MotivoAmenazaId { get; set; }
        public Nullable<int> MedioAmenazaId { get; set; }
        public Nullable<int> TipoIntrusionId { get; set; }
        public string Calle { get; set; }
        public string Colonia { get; set; }
        public string EntreCalles { get; set; }
        public Nullable<bool> ConVehiculo { get; set; }
    
        public virtual TipoArma TipoArma { get; set; }
        public virtual TipoExtorsion TipoExtorsion { get; set; }
        public virtual CantidadDelincuentes CantidadDelincuente { get; set; }
        public virtual Lesionado Lesionado { get; set; }
        public virtual MedioAmenaza MedioAmenaza { get; set; }
        public virtual TipoIntrusion TipoIntrusion { get; set; }
        public virtual TipoVehiculo TipoVehiculo { get; set; }
        public virtual TipoIncidente TipoIncidente { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Ciudad Ciudad { get; set; }
        public virtual Zona Zona { get; set; }
        public virtual Instalacion Instalaciones { get; set; }
        public virtual ICollection<AfectacionIncidente> AfectacionIncidentes { get; set; }
        public virtual MotivoAmenaza MotivoAmenaza { get; set; }
        public virtual TipoInstalacion TipoInstalacion { get; set; }
    }
    
}
