//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SS.Core.Entities
{
    public partial class ParametrosSistema
    {
        public ParametrosSistema()
        {
            this.ParametrosSistemaEmpresas = new HashSet<ParametroSistemaEmpresa>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int TipoDeParametro { get; set; }
        public bool TipoIncidenteEsRequerido { get; set; }
        public bool ValorFinalEsRequerido { get; set; }
    
        public virtual ICollection<ParametroSistemaEmpresa> ParametrosSistemaEmpresas { get; set; }
    }
    
}
