//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace SS.Core.Entities
{
    public partial class RiinContainer : DbContext
    {
        public RiinContainer()
            : base("name=RiinContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CantidadDelincuentes> CantidadDelincuentes { get; set; }
        public DbSet<Estado> Estados { get; set; }
        public DbSet<Ciudad> Ciudades { get; set; }
        public DbSet<Empresa> Empresas { get; set; }
        public DbSet<Incidente> Incidentes { get; set; }
        public DbSet<Instalacion> Instalaciones { get; set; }
        public DbSet<Lesionado> Lesionados { get; set; }
        public DbSet<MedioAmenaza> MediosAmenaza { get; set; }
        public DbSet<Perfil> Perfiles { get; set; }
        public DbSet<Poligono> Poligonos { get; set; }
        public DbSet<UsuarioPerfil> relPerfilesUsuarios { get; set; }
        public DbSet<MotivoAmenaza> MotivosAmenaza { get; set; }
        public DbSet<TipoArma> TiposArma { get; set; }
        public DbSet<TipoExtorsion> TiposExtorsion { get; set; }
        public DbSet<TipoIncidente> TiposIncidente { get; set; }
        public DbSet<TipoInstalacion> TiposInstalacion { get; set; }
        public DbSet<TipoIntrusion> TiposIntrusion { get; set; }
        public DbSet<TipoVehiculo> TiposVehiculo { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
        public DbSet<Zona> Zonas { get; set; }
        public DbSet<AlertaIncidente> AlertasIncidente { get; set; }
        public DbSet<ParametroSistemaEmpresa> ParametrosSistemaEmpresa { get; set; }
        public DbSet<ConfiguracionDashboard> ConfiguracionesDashboard { get; set; }
        public DbSet<NivelGeografico> NivelesGeograficos { get; set; }
        public DbSet<TipoUnidadTiempo> TiposUnidadTiempo { get; set; }
        public DbSet<ParametrosSistema> ParametrosSistema { get; set; }
        public DbSet<FiltroDashboard> FiltrosDashboard { get; set; }
        public DbSet<TipoFiltroDashboard> TiposFiltroDashboard { get; set; }
        public DbSet<PoligonoDetalle> PoligonosDetalle { get; set; }
        public DbSet<ReporteDashboard> ReportesDashboard { get; set; }
        public DbSet<TipoAfectacion> TiposAfectacion { get; set; }
        public DbSet<AfectacionIncidente> AfectacionesIncidente { get; set; }
        public DbSet<UsuarioEmpresa> relUsuarioEmpresa { get; set; }
    }
}
