//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SS.Core.Entities
{
    public partial class TipoIncidente
    {
        public TipoIncidente()
        {
            this.Incidentes = new HashSet<Incidente>();
            this.AlertaIncidentes = new HashSet<AlertaIncidente>();
            this.ParametroSistemaEmpresa = new HashSet<ParametroSistemaEmpresa>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public string Imagen { get; set; }
    
        public virtual ICollection<Incidente> Incidentes { get; set; }
        public virtual ICollection<AlertaIncidente> AlertaIncidentes { get; set; }
        public virtual ICollection<ParametroSistemaEmpresa> ParametroSistemaEmpresa { get; set; }
    }
    
}
