//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SS.Core.Entities
{
    public partial class Usuario
    {
        public Usuario()
        {
            this.Incidentes = new HashSet<Incidente>();
            this.UsuarioPerfiles = new HashSet<UsuarioPerfil>();
            this.UsuarioEmpresa = new HashSet<UsuarioEmpresa>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Email { get; set; }
        public bool Activo { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioBaja { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public Nullable<System.DateTime> FechaUltimoLogin { get; set; }
        public Nullable<bool> Bloqueado { get; set; }
    
        public virtual ICollection<Incidente> Incidentes { get; set; }
        public virtual ICollection<UsuarioPerfil> UsuarioPerfiles { get; set; }
        public virtual ICollection<UsuarioEmpresa> UsuarioEmpresa { get; set; }
    }
    
}
