//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSeguridad.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SistemaSeguridad.Resources.GlobalStrings", typeof(GlobalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea perder los cambios?.
        /// </summary>
        public static string CancelConfirm {
            get {
                return ResourceManager.GetString("CancelConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El elemento de cantidad de delincuentes seleccionado ha sido eliminado del sistema..
        /// </summary>
        public static string CantidadDelincuentesEliminado {
            get {
                return ResourceManager.GetString("CantidadDelincuentesEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar este tipo de cantidad de delincuentes..
        /// </summary>
        public static string CantidadDelincuentesRN {
            get {
                return ResourceManager.GetString("CantidadDelincuentesRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ciudad seleccionada ha sido eliminada del sistema..
        /// </summary>
        public static string CiudadEliminada {
            get {
                return ResourceManager.GetString("CiudadEliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar esta ciudad, por que tiene Incidentes asociados..
        /// </summary>
        public static string CiudadRN {
            get {
                return ResourceManager.GetString("CiudadRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor de confirmar el Estado, Ciudad y Zona..
        /// </summary>
        public static string ConfirmarGeolocalizacionIncidente {
            get {
                return ResourceManager.GetString("ConfirmarGeolocalizacionIncidente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha enviado su contraseña al correo electrónico que especifico cuando se dio de alta en el sistema..
        /// </summary>
        public static string ContraseñaEnviada {
            get {
                return ResourceManager.GetString("ContraseñaEnviada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrio un error al enviar su contraseña. Favor de contactar al administrador..
        /// </summary>
        public static string ContraseñaErrorAlEnviar {
            get {
                return ResourceManager.GetString("ContraseñaErrorAlEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de alta.
        /// </summary>
        public static string CreatorDate {
            get {
                return ResourceManager.GetString("CreatorDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario de alta.
        /// </summary>
        public static string CreatorUser {
            get {
                return ResourceManager.GetString("CreatorUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta seguro que desea borrar este elemento?.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string EditarPoligono {
            get {
                return ResourceManager.GetString("EditarPoligono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La empresa seleccionada ha sido eliminada del sistema..
        /// </summary>
        public static string EmpresaEliminada {
            get {
                return ResourceManager.GetString("EmpresaEliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar esta empresa, por que tiene Incidentes, Alertas Incidentes,  Instalaciones, Parametros Sistemas Empresas ó Usuario Empresa , asociados..
        /// </summary>
        public static string EmpresaRN {
            get {
                return ResourceManager.GetString("EmpresaRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrio un error, favor de verificar..
        /// </summary>
        public static string ErrorGeneral {
            get {
                return ResourceManager.GetString("ErrorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estado seleccionado ha sido eliminado del sistema..
        /// </summary>
        public static string EstadoEliminado {
            get {
                return ResourceManager.GetString("EstadoEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar este estado, por que tiene Incidentes, Ciudades o Zonas asociadas..
        /// </summary>
        public static string EstadoRN {
            get {
                return ResourceManager.GetString("EstadoRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontro una zona en esta localización, el incidente se marcara como fuera de zona..
        /// </summary>
        public static string IncidenteSinZona {
            get {
                return ResourceManager.GetString("IncidenteSinZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información.
        /// </summary>
        public static string Informacion {
            get {
                return ResourceManager.GetString("Informacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrio un error, contacte a su administrador..
        /// </summary>
        public static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo especificado, no coincide con el correo asiciado a este usuario. Favor de verificar..
        /// </summary>
        public static string InvalidMail {
            get {
                return ResourceManager.GetString("InvalidMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiar.
        /// </summary>
        public static string LimpiarMapa {
            get {
                return ResourceManager.GetString("LimpiarMapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parametro seleccionado ha sido eliminado del sistema..
        /// </summary>
        public static string ParametroEliminado {
            get {
                return ResourceManager.GetString("ParametroEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar esta parametro, por que tiene Incidentes asociados..
        /// </summary>
        public static string ParametroRN {
            get {
                return ResourceManager.GetString("ParametroRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea regresar?.
        /// </summary>
        public static string ReturnConfirm {
            get {
                return ResourceManager.GetString("ReturnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Seleccione uno -.
        /// </summary>
        public static string selectOne {
            get {
                return ResourceManager.GetString("selectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de afectacion seleccionado ha sido eliminado del sistema..
        /// </summary>
        public static string TipoAfectacionEliminada {
            get {
                return ResourceManager.GetString("TipoAfectacionEliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar este tipo de afectacion, por que tiene Afectacion Incidentes asociados..
        /// </summary>
        public static string TipoAfectacionRN {
            get {
                return ResourceManager.GetString("TipoAfectacionRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de arma seleccionado ha sido eliminado del sistema..
        /// </summary>
        public static string TipoArmaEliminada {
            get {
                return ResourceManager.GetString("TipoArmaEliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar este tipo de arma, por que tiene Incidentes asociados..
        /// </summary>
        public static string TipoArmaRN {
            get {
                return ResourceManager.GetString("TipoArmaRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de incidente seleccionado ha sido eliminado del sistema..
        /// </summary>
        public static string TipoIncidenteEliminado {
            get {
                return ResourceManager.GetString("TipoIncidenteEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar este tipo de incidente, por que tiene Alerta Incidentes, Incidentes o Parametro Sistema Empresa asociados..
        /// </summary>
        public static string TipoIncidenteRN {
            get {
                return ResourceManager.GetString("TipoIncidenteRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de instalacion seleccionado ha sido eliminado del sistema..
        /// </summary>
        public static string TipoInstalacionEliminada {
            get {
                return ResourceManager.GetString("TipoInstalacionEliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar este tipo de instalacion, por que tiene Incidentes asociados..
        /// </summary>
        public static string TipoInstalacionRN {
            get {
                return ResourceManager.GetString("TipoInstalacionRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de intrusión seleccionado ha sido eliminado del sistema..
        /// </summary>
        public static string TipoIntrusionEliminado {
            get {
                return ResourceManager.GetString("TipoIntrusionEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar este tipo de intrusión..
        /// </summary>
        public static string TipoIntrusionRN {
            get {
                return ResourceManager.GetString("TipoIntrusionRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de lesionado seleccionado ha sido eliminado del sistema..
        /// </summary>
        public static string TipoLesionadoEliminado {
            get {
                return ResourceManager.GetString("TipoLesionadoEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar este tipo de lesión, por que tiene Incidentes asociados..
        /// </summary>
        public static string TipoLesionadoRN {
            get {
                return ResourceManager.GetString("TipoLesionadoRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario seleccionado ha sido eliminado del sistema..
        /// </summary>
        public static string Usuario_eliminado {
            get {
                return ResourceManager.GetString("Usuario_eliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar este usuario, por que tiene Incidentes asociados..
        /// </summary>
        public static string Usuario_RN {
            get {
                return ResourceManager.GetString("Usuario_RN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por su seguridad, esta cuenta a sido bloqueada, favor de consultar con su administrador..
        /// </summary>
        public static string UsuarioBloqueado {
            get {
                return ResourceManager.GetString("UsuarioBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario Usuario se ha dado de alta exitosamente..
        /// </summary>
        public static string UsuarioCreado {
            get {
                return ResourceManager.GetString("UsuarioCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario especificado se encuentra inactivo..
        /// </summary>
        public static string UsuarioInactivo {
            get {
                return ResourceManager.GetString("UsuarioInactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario especificado no existe..
        /// </summary>
        public static string UsuarioInexistente {
            get {
                return ResourceManager.GetString("UsuarioInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El password que ingreso, es incorrecto, favor de verificar..
        /// </summary>
        public static string UsuarioPassword {
            get {
                return ResourceManager.GetString("UsuarioPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario o password que ingreso, estan incorrectos. Favor de verificar..
        /// </summary>
        public static string UsuarioPasswordIncorrecto {
            get {
                return ResourceManager.GetString("UsuarioPasswordIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La zona seleccionada ha sido eliminada del sistema..
        /// </summary>
        public static string ZonaEliminada {
            get {
                return ResourceManager.GetString("ZonaEliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar esta zona, por que tiene Incidentes asociados..
        /// </summary>
        public static string ZonaRN {
            get {
                return ResourceManager.GetString("ZonaRN", resourceCulture);
            }
        }
    }
}
