using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SS.Core.Entities;

namespace SistemaSeguridad.Models
{
    public class EmpresaEntity : Empresa
    {
        /// <summary>
        /// This property is a wrapper for field Id
        /// Its used in DropDowns DON'T DELETE IT
        /// </summary>
        public int? EmpresaId
        {
            //Is nullable to allow saving when is group
            get { return base.Id; }
            set { base.Id = value ?? 0; }
        }

        //public int? GrupoId
        //{
        //    get { return base.GrupoId; }
        //    set { base.GrupoId = value ?? 0; }
        //}
    }
}



//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//using System;
//using System.Collections.Generic;
//using System.ComponentModel.DataAnnotations;

//namespace SistemaSeguridad.Models
//{
//    public partial class Empresa
//    {
//        public Empresa()
//        {
//            this.Instalaciones = new HashSet<Instalacion>();
//            this.Incidentes = new HashSet<Incidente>();
//            this.AlertaIncidentes = new HashSet<AlertaIncidente>();
//            this.ParametrosSistemaEmpresas = new HashSet<ParametroSistemaEmpresa>();
//        }



//        public int Id { get; set; }

//        public bool TipoEmpresa { get; set; }


//        public int UsuarioAlta { get; set; }

//        [Required(ErrorMessage = "El Nombre es requerido")]
//        [StringLength(50, ErrorMessage = "{0} Debe de ser al menos {2} caracteres de largo.", MinimumLength = 6)]
//        [Display(Name = "Nombre")]
//        public string Nombre { get; set; }

//        //[Range(0, 5, ErrorMessage = "Number of credits must be between 0 and 5.")]
//        //[Display(Name = "Fecha de alta")]
//        //[DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true, NullDisplayText = "Sin Fecha")]
//        //[Required(ErrorMessage = "Fecha de alta es requerida")]
//        //[DataType(DataType.Date)]
//        public DateTime FechaAlta { get; set; }

//        public virtual ICollection<Instalacion> Instalaciones { get; set; }
//        public virtual ICollection<Incidente> Incidentes { get; set; }
//        public virtual ICollection<AlertaIncidente> AlertaIncidentes { get; set; }
//        public virtual ICollection<ParametroSistemaEmpresa> ParametrosSistemaEmpresas { get; set; }
//    }

//}
