//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estados
    {
        public Estados()
        {
            this.Ciudades = new HashSet<Ciudades>();
            this.Incidentes = new HashSet<Incidentes>();
            this.Zonas = new HashSet<Zonas>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> PoligonoId { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
    
        public virtual ICollection<Ciudades> Ciudades { get; set; }
        public virtual ICollection<Incidentes> Incidentes { get; set; }
        public virtual Poligonos Poligonos { get; set; }
        public virtual ICollection<Zonas> Zonas { get; set; }
    }
}
