//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FiltrosDashboard
    {
        public int Id { get; set; }
        public int FiltroDashboardId { get; set; }
        public int TipoFiltroId { get; set; }
        public int ValorFiltro { get; set; }
    
        public virtual ConfiguracionesDashboard ConfiguracionesDashboard { get; set; }
        public virtual TiposFiltroDashboard TiposFiltroDashboard { get; set; }
    }
}
