//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidentes
    {
        public Incidentes()
        {
            this.AfectacionesIncidente = new HashSet<AfectacionesIncidente>();
        }
    
        public int Id { get; set; }
        public System.DateTime FechaIncidente { get; set; }
        public int EmpresaId { get; set; }
        public int TipoIncidenteId { get; set; }
        public Nullable<int> LesionadosId { get; set; }
        public Nullable<int> TipoInstalacionId { get; set; }
        public Nullable<int> InstalacionId { get; set; }
        public Nullable<decimal> MontoAfectacion { get; set; }
        public string Comentarios { get; set; }
        public double Latitud { get; set; }
        public double Longitud { get; set; }
        public int EstadoId { get; set; }
        public int CiudadId { get; set; }
        public Nullable<int> ZonaId { get; set; }
        public Nullable<int> TipoArmaId { get; set; }
        public Nullable<bool> Detenidos { get; set; }
        public Nullable<int> CantidadDelincuentesId { get; set; }
        public Nullable<int> TipoVehiculoId { get; set; }
        public Nullable<int> TipoExtorsionId { get; set; }
        public int UsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioCancelacion { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public Nullable<int> UsuarioUltimaModificacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaMoldificacion { get; set; }
        public Nullable<int> MotivoAmenazaId { get; set; }
        public Nullable<int> MedioAmenazaId { get; set; }
        public Nullable<int> TipoIntrusionId { get; set; }
        public string Calle { get; set; }
        public string Colonia { get; set; }
        public string EntreCalles { get; set; }
        public Nullable<bool> ConVehiculo { get; set; }
    
        public virtual ICollection<AfectacionesIncidente> AfectacionesIncidente { get; set; }
        public virtual CantidadDelincuentes CantidadDelincuentes { get; set; }
        public virtual Ciudades Ciudades { get; set; }
        public virtual Empresas Empresas { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual Instalaciones Instalaciones { get; set; }
        public virtual Lesionados Lesionados { get; set; }
        public virtual MediosAmenaza MediosAmenaza { get; set; }
        public virtual MotivosAmenaza MotivosAmenaza { get; set; }
        public virtual TiposArma TiposArma { get; set; }
        public virtual TiposExtorsion TiposExtorsion { get; set; }
        public virtual TiposIncidente TiposIncidente { get; set; }
        public virtual TiposInstalacion TiposInstalacion { get; set; }
        public virtual TiposIntrusion TiposIntrusion { get; set; }
        public virtual TiposVehiculo TiposVehiculo { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Zonas Zonas { get; set; }
    }
}
