//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformacionEstados
    {
        public string Nombre { get; set; }
        public string Expr1 { get; set; }
        public Nullable<int> Id { get; set; }
        public Nullable<System.DateTime> FechaIncidente { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public Nullable<int> TipoIncidenteId { get; set; }
        public Nullable<int> LesionadosId { get; set; }
        public Nullable<int> TipoInstalacionId { get; set; }
        public Nullable<int> InstalacionId { get; set; }
        public Nullable<decimal> MontoAfectacion { get; set; }
        public string Comentarios { get; set; }
        public Nullable<double> Latitud { get; set; }
        public Nullable<double> Longitud { get; set; }
        public Nullable<int> EstadoId { get; set; }
        public Nullable<int> CiudadId { get; set; }
        public Nullable<int> ZonaId { get; set; }
        public Nullable<int> TipoArmaId { get; set; }
        public Nullable<bool> Detenidos { get; set; }
        public Nullable<int> CantidadDelincuentesId { get; set; }
        public Nullable<int> TipoVehiculoId { get; set; }
        public Nullable<int> TipoExtorsionId { get; set; }
        public Nullable<int> UsuarioAlta { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> UsuarioCancelacion { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public Nullable<int> UsuarioUltimaModificacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaMoldificacion { get; set; }
        public Nullable<int> MotivoAmenazaId { get; set; }
        public Nullable<int> MedioAmenazaId { get; set; }
        public Nullable<int> TipoIntrusionId { get; set; }
        public string Calle { get; set; }
        public string Colonia { get; set; }
        public string EntreCalles { get; set; }
        public Nullable<bool> ConVehiculo { get; set; }
    }
}
