//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametrosSistema
    {
        public ParametrosSistema()
        {
            this.ParametrosSistemaEmpresa = new HashSet<ParametrosSistemaEmpresa>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int TipoDeParametro { get; set; }
        public bool TipoIncidenteEsRequerido { get; set; }
        public bool ValorFinalEsRequerido { get; set; }
    
        public virtual ICollection<ParametrosSistemaEmpresa> ParametrosSistemaEmpresa { get; set; }
    }
}
