//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoligonosDetalle
    {
        public int Id { get; set; }
        public int PoligonoId { get; set; }
        public double Latitud { get; set; }
        public double Longitud { get; set; }
    
        public virtual Poligonos Poligonos { get; set; }
    }
}
