//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportesDashboard
    {
        public ReportesDashboard()
        {
            this.ConfiguracionesDashboard = new HashSet<ConfiguracionesDashboard>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<ConfiguracionesDashboard> ConfiguracionesDashboard { get; set; }
    }
}
