//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Core.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RIINEntities : DbContext
    {
        public RIINEntities()
            : base("name=RIINEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AfectacionesIncidente> AfectacionesIncidente { get; set; }
        public DbSet<AlertasIncidente> AlertasIncidente { get; set; }
        public DbSet<CantidadDelincuentes> CantidadDelincuentes { get; set; }
        public DbSet<Ciudades> Ciudades { get; set; }
        public DbSet<ConfiguracionesDashboard> ConfiguracionesDashboard { get; set; }
        public DbSet<Empresas> Empresas { get; set; }
        public DbSet<Estados> Estados { get; set; }
        public DbSet<FiltrosDashboard> FiltrosDashboard { get; set; }
        public DbSet<Incidentes> Incidentes { get; set; }
        public DbSet<Instalaciones> Instalaciones { get; set; }
        public DbSet<Lesionados> Lesionados { get; set; }
        public DbSet<MediosAmenaza> MediosAmenaza { get; set; }
        public DbSet<MotivosAmenaza> MotivosAmenaza { get; set; }
        public DbSet<NivelesGeograficos> NivelesGeograficos { get; set; }
        public DbSet<ParametrosSistema> ParametrosSistema { get; set; }
        public DbSet<ParametrosSistemaEmpresa> ParametrosSistemaEmpresa { get; set; }
        public DbSet<Perfiles> Perfiles { get; set; }
        public DbSet<Poligonos> Poligonos { get; set; }
        public DbSet<PoligonosDetalle> PoligonosDetalle { get; set; }
        public DbSet<ReportesDashboard> ReportesDashboard { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TiposAfectacion> TiposAfectacion { get; set; }
        public DbSet<TiposArma> TiposArma { get; set; }
        public DbSet<TiposExtorsion> TiposExtorsion { get; set; }
        public DbSet<TiposFiltroDashboard> TiposFiltroDashboard { get; set; }
        public DbSet<TiposIncidente> TiposIncidente { get; set; }
        public DbSet<TiposInstalacion> TiposInstalacion { get; set; }
        public DbSet<TiposIntrusion> TiposIntrusion { get; set; }
        public DbSet<TiposUnidadTiempo> TiposUnidadTiempo { get; set; }
        public DbSet<TiposVehiculo> TiposVehiculo { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
        public DbSet<Zonas> Zonas { get; set; }
        public DbSet<InformacionEmpresas> InformacionEmpresas { get; set; }
        public DbSet<InformacionEstados> InformacionEstados { get; set; }
        public DbSet<InformacionPerfiles> InformacionPerfiles { get; set; }
    }
}
